const C = {
  CATALOG_LOADED: 'CATALOG_LOADED',
  CATALOG_ERROR: 'CATALOG_ERROR',
  SELECT_ITEM: 'SELECT_ITEM',
  SELECT_AMOUNT: 'SELECT_AMOUNT',
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_FROM_CART: 'DELETE_FROM_CART',
  CHANGE_AMOUNT_IN_CART: 'CHANGE_AMOUNT_IN_CART',
  TOGGLE_MODAL: 'TOGGLE_MODAL'
};

export default C;
